sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vallabhanenichaitanya/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true vallabhanenichaitanya/docker-react npm run test